
# This Docker Compose file should only be used for your development environment!
version: '3.5'

services:

  traefik:
    image: traefik:2.4
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --api.dashboard=true
      - --api.insecure=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_dashboard_router.rule=Host(`traefik.$DOMAIN`)
      - traefik.http.routers.traefik_dashboard_router.service=traefik_dashboard_service
      - traefik.http.services.traefik_dashboard_service.loadbalancer.server.port=8080
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: "./src/api"
    labels:
      - traefik.enable=true
      - traefik.http.routers.api_router.rule=Host(`$API_SUBDOMAIN.$DOMAIN`)
      - traefik.http.routers.api_router.service=api_service
      - traefik.http.services.api_service.loadbalancer.server.port=$API_PORT
    ports:
      - "${API_PORT}:${API_PORT}"
    command: pnpm dev:api
    environment:
      # Docker image.
      # ---------------------
      STARTUP_COMMAND_1: "pnpm install"
      STARTUP_COMMAND_2: "pnpm dev:build"
      APP_NAME: "$APP_NAME"
      APP_VERSION: "$APP_VERSION"
      API_PORT: "$API_PORT"

    volumes:
      - ./src/api:/usr/src/app
      - ~/.ssh:/home/docker/.ssh:ro

networks:
  default:
    name: 2aud.io-network


